# Generated by Django 4.2.15 on 2024-09-04 09:07

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/group_profiles'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
