# Generated by Django 4.2.15 on 2024-09-06 12:41

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_group_group_name_alter_group_group_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
