# Generated by Django 4.2.15 on 2024-10-02 16:58

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_group_group_name_alter_groupmessage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'get_latest_by': ['created'], 'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='group',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatgroup_lastmessage', to='chat.groupmessage', to_field='created'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
