# Generated by Django 5.1 on 2024-08-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
